### ISSUE TITLE
[问题反馈]: 图床报错

### ISSUE THREAD

**Issue by 8ty** [Mereithhh/vanblog#126]
### 问题描述 | Describe the bug

日记：
`````
[Nest] 18  - 01/18/2023, 12:28:51 PM     LOG [PicgoProvider] 尝试安装 picgo 插件：github
npm notice 
npm notice New minor version of npm available! 9.2.0 -> 9.3.1
npm notice Changelog: https://github.com/npm/cli/releases/tag/v9.3.1
npm notice Run npm install -g npm@9.3.1 to update!
npm notice 
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/picgo-plugin-github - Not found
npm ERR! 404 
npm ERR! 404  'picgo-plugin-github@*' is not in this registry.
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-01-18T04_28_55_188Z-debug-0.log
[PicGo ERROR]: 插件安装失败，失败码为1，错误日志为npm notice 
npm notice New minor version of npm available! 9.2.0 -> 9.3.1
npm notice Changelog: https://github.com/npm/cli/releases/tag/v9.3.1
npm notice Run npm install -g npm@9.3.1 to update!
npm notice 
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/picgo-plugin-github - Not found
npm ERR! 404 
npm ERR! 404  'picgo-plugin-github@*' is not in this registry.
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-01-18T04_28_55_188Z-debug-0.log

[Nest] 18  - 01/18/2023, 12:28:56 PM   ERROR [PicgoProvider] picgo 插件安装失败！插件安装失败，失败码为1，错误日志为npm notice 
npm notice New minor version of npm available! 9.2.0 -> 9.3.1
npm notice Changelog: https://github.com/npm/cli/releases/tag/v9.3.1
npm notice Run npm install -g npm@9.3.1 to update!
npm notice 
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/picgo-plugin-github - Not found
npm ERR! 404 
npm ERR! 404  'picgo-plugin-github@*' is not in this registry.
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-01-18T04_28_55_188Z-debug-0.log

[Nest] 18  - 01/18/2023, 12:54:09 PM   ERROR [WalineProvider] UnauthorizedError: Unauthorized
    at Object.throw (/app/walinede_modules/koab/context.js:97:11)
    at module.exports.postAction (/app/walinede_modules/@walineercelc/logic/comment.js:217:28)
    at /app/walinede_modules/think-logic/index.js:51:37
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

``````
看来好像是没有这个插件？

### 版本 | Version

最新

### 部署方式？ | How do you deploy vanblog?

Docker 部署(文档默认)

**Comment by Mereithhh** [comment]
群友遇到了这个问题，经过排查发现。
使用内置支持的 github 等图床时，后台图床设置中下面的自定义插件要留空，不然会尝试安装 github 插件，但实际上是内置的，不算插件，找不到就报错咯。

试试看，能解决问题不？

**Comment by 8ty** [comment]
好的
不过我在找客服要了个ipv6的地址后就莫名其妙可以了，所以我觉得是因为vps向github通信时定向到ipv6了，所以会发生错误
