### ISSUE TITLE
[问题反馈]: 更新到v0.45.6后重启服务所有内容消失

### ISSUE THREAD

**Issue by 6uu1** [Mereithhh/vanblog#160]
### 问题描述 | Describe the bug

![image](https://user-images.githubusercontent.com/122669698/220306118-e60132ac-f148-41aa-88fb-deaf3b31a913.png)

### 复现网址 | Website URL

https://696988.xyz/

### 版本 | Version

v0.45.6

### 部署方式？ | How do you deploy vanblog?

Docker 部署(文档默认)

**Comment by 6uu1** [comment]
出错日记：
``````
vanblog_1  | [Nest] 17  - 02/21/2023, 5:33:29 PM    WARN [ISRProvider] 第3次重试触发增量渲染！来源：首次启动触发全量渲染！
vanblog_1  | [Nest] 17  - 02/21/2023, 5:33:33 PM   ERROR [WebsiteProvider] Error: Minified React error #62; visit https://reactjs.org/docs/error-decoder.html?invariant=62 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
vanblog_1  |     at Fa (/app/website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:27:49)
vanblog_1  |     at I (/app/website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:29:44)
vanblog_1  |     at Ka (/app/website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:32:184)
vanblog_1  |     at Pa (/app/website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:38:360)
vanblog_1  |     at Mc (/app/website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:67:38)
vanblog_1  |     at Z (/app/website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:71:89)
vanblog_1  |     at Nc (/app/website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:73:98)
vanblog_1  |     at Pc (/app/website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:72:306)
vanblog_1  |     at Z (/app/website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:71:217)
vanblog_1  |     at Nc (/app/website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:73:98)
vanblog_1  | [Nest] 17  - 02/21/2023, 5:33:33 PM   ERROR [WebsiteProvider] Error: Minified React error #62; visit https://reactjs.org/docs/error-decoder.html?invariant=62 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
vanblog_1  |     at Fa (/app/website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:27:49)
vanblog_1  |     at I (/app/website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:29:44)
vanblog_1  |     at Ka (/app/website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:32:184)
vanblog_1  |     at Pa (/app/website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:38:360)
vanblog_1  |     at Mc (/app/website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:67:38)
vanblog_1  |     at Z (/app/website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:71:89)
vanblog_1  |     at Nc (/app/website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:73:98)
vanblog_1  |     at Pc (/app/website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:72:306)
vanblog_1  |     at Z (/app/website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:71:217)
vanblog_1  |     at Nc (/app/website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:73:98)
vanblog_1  | [Nest] 17  - 02/21/2023, 5:33:33 PM   ERROR [WebsiteProvider] TypeError: res.hasHeader is not a function
vanblog_1  |     at Object.setRevalidateHeaders (/app/website/node_modules/next/dist/server/send-payload/revalidate-headers.js:8:37)
vanblog_1  |     at Object.sendRenderResult (/app/website/node_modules/next/dist/server/send-payload/index.js:62:33)
vanblog_1  | [Nest] 17  - 02/21/2023, 5:33:33 PM     LOG [WebsiteProvider] Error: Failed to revalidate /: Invalid response 500
vanblog_1  |     at revalidate (/app/website/node_modules/next/dist/server/api-utils/node.js:306:15)
vanblog_1  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
vanblog_1  |     at async handler (/app/website/.next/server/pages/api/revalidate.js:23:9)
vanblog_1  |     at async Object.apiResolver (/app/website/node_modules/next/dist/server/api-utils/node.js:372:9)
vanblog_1  |     at async NextNodeServer.runApi (/app/website/node_modules/next/dist/server/next-server.js:488:9)
vanblog_1  |     at async Object.fn (/app/website/node_modules/next/dist/server/next-server.js:751:37)
vanblog_1  |     at async Router.execute (/app/website/node_modules/next/dist/server/router.js:253:36)
vanblog_1  |     at async NextNodeServer.run (/app/website/node_modules/next/dist/server/base-server.js:384:29)
vanblog_1  |     at async NextNodeServer.handleRequest (/app/website/node_modules/next/dist/server/base-server.js:322:20)
vanblog_1  | [Nest] 17  - 02/21/2023, 5:33:33 PM    WARN [ISRProvider] 第4次重试触发增量渲染！来源：首次启动触发全量渲染！
vanblog_1  | [Nest] 17  - 02/21/2023, 5:33:36 PM   ERROR [WebsiteProvider] Error: Minified React error #62; visit https://reactjs.org/docs/error-decoder.html?invariant=62 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
vanblog_1  |     at Fa (/app/website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:27:49)
vanblog_1  |     at I (/app/website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:29:44)
vanblog_1  |     at Ka (/app/website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:32:184)
vanblog_1  |     at Pa (/app/website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:38:360)
vanblog_1  |     at Mc (/app/website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:67:38)
vanblog_1  |     at Z (/app/website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:71:89)
vanblog_1  |     at Nc (/app/website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:73:98)
vanblog_1  |     at Pc (/app/website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:72:306)
vanblog_1  |     at Z (/app/website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:71:217)
vanblog_1  |     at Nc (/app/website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:73:98)
vanblog_1  | [Nest] 17  - 02/21/2023, 5:33:36 PM   ERROR [WebsiteProvider] Error: Minified React error #62; visit https://reactjs.org/docs/error-decoder.html?invariant=62 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
vanblog_1  |     at Fa (/app/website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:27:49)
vanblog_1  |     at I (/app/website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:29:44)
vanblog_1  |     at Ka (/app/website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:32:184)
vanblog_1  |     at Pa (/app/website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:38:360)
vanblog_1  |     at Mc (/app/website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:67:38)
vanblog_1  |     at Z (/app/website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:71:89)
vanblog_1  |     at Nc (/app/website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:73:98)
vanblog_1  |     at Pc (/app/website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:72:306)
vanblog_1  |     at Z (/app/website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:71:217)
vanblog_1  |     at Nc (/app/website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:73:98)
vanblog_1  | [Nest] 17  - 02/21/2023, 5:33:36 PM   ERROR [WebsiteProvider] TypeError: res.hasHeader is not a function
vanblog_1  |     at Object.setRevalidateHeaders (/app/website/node_modules/next/dist/server/send-payload/revalidate-headers.js:8:37)
vanblog_1  |     at Object.sendRenderResult (/app/website/node_modules/next/dist/server/send-payload/index.js:62:33)
vanblog_1  | [Nest] 17  - 02/21/2023, 5:33:36 PM     LOG [WebsiteProvider] Error: Failed to revalidate /: Invalid response 500
vanblog_1  |     at revalidate (/app/website/node_modules/next/dist/server/api-utils/node.js:306:15)
vanblog_1  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
vanblog_1  |     at async handler (/app/website/.next/server/pages/api/revalidate.js:23:9)
vanblog_1  |     at async Object.apiResolver (/app/website/node_modules/next/dist/server/api-utils/node.js:372:9)
vanblog_1  |     at async NextNodeServer.runApi (/app/website/node_modules/next/dist/server/next-server.js:488:9)
vanblog_1  |     at async Object.fn (/app/website/node_modules/next/dist/server/next-server.js:751:37)
vanblog_1  |     at async Router.execute (/app/website/node_modules/next/dist/server/router.js:253:36)
vanblog_1  |     at async NextNodeServer.run (/app/website/node_modules/next/dist/server/base-server.js:384:29)
vanblog_1  |     at async NextNodeServer.handleRequest (/app/website/node_modules/next/dist/server/base-server.js:322:20)
vanblog_1  | [Nest] 17  - 02/21/2023, 5:33:36 PM    WARN [ISRProvider] 第5次重试触发增量渲染！来源：首次启动触发全量渲染！
vanblog_1  | [Nest] 17  - 02/21/2023, 5:33:39 PM   ERROR [ISRProvider] 达到最大增量渲染重试次数！来源：首次启动触发全量渲染！
vanblog_1  | [Nest] 17  - 02/21/2023, 5:33:48 PM     LOG [MetaProvider] 更新文章触发更新字数缓存：当前文章总字数: 44185
vanblog_1  | [Nest] 17  - 02/21/2023, 5:34:19 PM     LOG [SiteMapProvider] 更新文章触发增量渲染！重新生成 SiteMap 
vanblog_1  | [Nest] 17  - 02/21/2023, 5:34:33 PM   ERROR [WebsiteProvider] Error: Minified React error #62; visit https://reactjs.org/docs/error-decoder.html?invariant=62 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
vanblog_1  |     at Fa (/app/website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:27:49)
vanblog_1  |     at I (/app/website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:29:44)
vanblog_1  |     at Ka (/app/website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:32:184)
vanblog_1  |     at Pa (/app/website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:38:360)
vanblog_1  |     at Mc (/app/website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:67:38)
vanblog_1  |     at Z (/app/website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:71:89)
vanblog_1  |     at Nc (/app/website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:73:98)
vanblog_1  |     at Pc (/app/website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:72:306)
vanblog_1  |     at Z (/app/website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:71:217)
vanblog_1  |     at Nc (/app/website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:73:98)
vanblog_1  | [Nest] 17  - 02/21/2023, 5:34:33 PM   ERROR [WebsiteProvider] Error: Minified React error #62; visit https://reactjs.org/docs/error-decoder.html?invariant=62 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
vanblog_1  |     at Fa (/app/website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:27:49)
vanblog_1  |     at I (/app/website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:29:44)
vanblog_1  |     at Ka (/app/website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:32:184)
vanblog_1  |     at Pa (/app/website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:38:360)
vanblog_1  |     at Mc (/app/website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:67:38)
vanblog_1  |     at Z (/app/website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:71:89)
vanblog_1  |     at Nc (/app/website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:73:98)
vanblog_1  |     at Pc (/app/website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:72:306)
vanblog_1  |     at Z (/app/website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:71:217)
vanblog_1  |     at Nc (/app/website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:73:98)
mongo_1    | {"t":{"$date":"2023-02-21T17:35:59.842+08:00"},"s":"I",  "c":"STORAGE",  "id":22430,   "ctx":"WTCheckpointThread","msg":"WiredTiger message","attr":{"message":"[1676972159:842559][1:0x7f51145c1700], WT_SESSION.checkpoint: [WT_VERB_CHECKPOINT_PROGRESS] saving checkpoint snapshot min: 105, snapshot max: 105 snapshot count: 0, oldest timestamp: (0, 0) , meta checkpoint timestamp: (0, 0) base write gen: 175051"}}
vanblog_1  | [Nest] 17  - 02/21/2023, 5:36:19 PM     LOG [RssProvider] 更新文章触发增量渲染！重新生成 RSS 订阅
mongo_1    | {"t":{"$date":"2023-02-21T17:36:59.912+08:00"},"s":"I",  "c":"STORAGE",  "id":22430,   "ctx":"WTCheckpointThread","msg":"WiredTiger message","attr":{"message":"[1676972219:912359][1:0x7f51145c1700], WT_SESSION.checkpoint: [WT_VERB_CHECKPOINT_PROGRESS] saving checkpoint snapshot min: 117, snapshot max: 117 snapshot count: 0, oldest timestamp: (0, 0) , meta checkpoint timestamp: (0, 0) base write gen: 175051"}}

``````

**Comment by Mereithhh** [comment]
几个问题：
- 之前是好的吗？
- 之前是什么版本？
- 除了升级，你还做了什么可能影响的操作没有？ 比如发布/创建文章。

**Comment by Mereithhh** [comment]
单看报错可能是由于文章中的不恰当使用了 html 标签导致的，你可以去掉首页文章中的 html 标签后重启服务，试试看会不会好起来。

**Comment by 6uu1** [comment]
> 几个问题：
> 
> * 之前是好的吗？
> * 之前是什么版本？
> * 除了升级，你还做了什么可能影响的操作没有？ 比如发布/创建文章。

1.之前是好的，刚刚升级的时候是好的，但是重启之后就这样子了
2.0.45.5
3.有创建文章，还加入了谷歌adsense的代码，现在排查一下是不是这个问题

**Comment by 6uu1** [comment]
> 单看报错可能是由于文章中的不恰当使用了 html 标签导致的，你可以去掉首页文章中的 html 标签后重启服务，试试看会不会好起来。

还有一个报错：
vanblog_1  | [Nest] 17  - 02/21/2023, 7:04:11 PM   ERROR [WebsiteProvider] TypeError: res.hasHeader is not a function

**Comment by 6uu1** [comment]
把内容全部清除掉现在恢复正常了

**Comment by 6uu1** [comment]
还有几个问题想要请教一下：
像这些的代码应该分别放在
![image](https://user-images.githubusercontent.com/122669698/220330839-58044139-f3f8-4d2f-bdfd-1969b5f10024.png)
这4个的哪里？
## 1.信息流广告
![image](https://user-images.githubusercontent.com/122669698/220330779-b2e0b089-aded-4ce8-992b-639602bf4f52.png)
## 2. 展示广告
![image](https://user-images.githubusercontent.com/122669698/220331213-5961c43d-a86f-4ecb-8521-88c5e0735a11.png)
## 3.文章内嵌（我尝试将这个放在创建文章的内容里面，但是好像不起作用，是不是因为md编辑器无法识别？）
![image](https://user-images.githubusercontent.com/122669698/220331695-9e047764-2018-40df-9f6a-e48b2238949b.png)

**Comment by Mereithhh** [comment]
你说的三点中的代码是一样的。 都放到客制化的自定义 HTML（body）中应该就行吧。你试试？

**Comment by Mereithhh** [comment]
不要在文章内放这些

**Comment by 6uu1** [comment]
> 你说的三点中的代码是一样的。 都放到客制化的自定义 HTML（body）中应该就行吧。你试试？

好的，感谢回复，我试试
