### ISSUE TITLE
[问题反馈]: 更新后上传图片出错

### ISSUE THREAD

**Issue by 6uu1** [Mereithhh/vanblog#285]
### 问题描述 | Describe the bug

日志：
``````
[Nest] 20  - 04/23/2023, 11:08:06 AM   ERROR [ExceptionsHandler] ENOENT: no such file or directory, lstat '/app/static/tmp/3477ff6986c3fe8bd99b3687dcb73c6d.clipboard-2023-04-23.webp'
vanblog_1  | Error: ENOENT: no such file or directory, lstat '/app/static/tmp/3477ff6986c3fe8bd99b3687dcb73c6d.clipboard-2023-04-23.webp'
vanblog_1  |     at Object.lstatSync (node:fs:1593:3)
vanblog_1  |     at __node_internal_ (node:internal/fs/utils:821:8)
vanblog_1  |     at Object.rmSync (node:fs:1273:13)
vanblog_1  |     at PicgoProvider.saveFile (/app/server/provider/static/picgo.provider.js:104:16)
vanblog_1  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
vanblog_1  |     at async StaticProvider.saveFile (/app/server/provider/static/static.provider.js:211:34)
vanblog_1  |     at async StaticProvider.upload (/app/server/provider/static/static.provider.js:90:26)
vanblog_1  |     at async ImgController.upload (/app/server/controller/admin/img/img.controller.js:38:21)
vanblog_1  | [PicGo INFO]: Before upload
vanblog_1  | [PicGo INFO]: Uploading... Current uploader is [web-uploader-custom-url-prefix]
vanblog_1  | Saving file '/tmp/temp1682219286762.webp'
vanblog_1  | File:      /tmp/temp1682219286762
vanblog_1  | Dimension: 755 x 636
vanblog_1  | Output:    936 bytes Y-U-V-All-PSNR 99.00 99.00 99.00   99.00 dB
vanblog_1  |            (0.02 bpp)
vanblog_1  | block count:  intra4:          0  (0.00%)
vanblog_1  |               intra16:      1920  (100.00%)
vanblog_1  |               skipped:      1919  (99.95%)
vanblog_1  | bytes used:  header:             21  (2.2%)
vanblog_1  |              mode-partition:    831  (88.8%)
vanblog_1  |  Residuals bytes  |segment 1|segment 2|segment 3|segment 4|  total
vanblog_1  |     macroblocks:  |       0%|       0%|       0%|     100%|    1920
vanblog_1  |       quantizer:  |      27 |      27 |      25 |      19 |
vanblog_1  |    filter level:  |       8 |       6 |       5 |       2 |
vanblog_1  | [PicGo SUCCESS]: 
vanblog_1  | 
vanblog_1  | [Nest] 20  - 04/23/2023, 11:08:07 AM   ERROR [ExceptionsHandler] ENOENT: no such file or directory, lstat '/app/static/tmp/3477ff6986c3fe8bd99b3687dcb73c6d.clipboard-2023-04-23.webp'
vanblog_1  | Error: ENOENT: no such file or directory, lstat '/app/static/tmp/3477ff6986c3fe8bd99b3687dcb73c6d.clipboard-2023-04-23.webp'
vanblog_1  |     at Object.lstatSync (node:fs:1593:3)
vanblog_1  |     at __node_internal_ (node:internal/fs/utils:821:8)
vanblog_1  |     at Object.rmSync (node:fs:1273:13)
vanblog_1  |     at PicgoProvider.saveFile (/app/server/provider/static/picgo.provider.js:104:16)
vanblog_1  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
vanblog_1  |     at async StaticProvider.saveFile (/app/server/provider/static/static.provider.js:211:34)
vanblog_1  |     at async StaticProvider.upload (/app/server/provider/static/static.provider.js:90:26)
vanblog_1  |     at async ImgController.upload (/app/server/controller/admin/img/img.controller.js:38:21)

`````

### 复现网址 | Website URL

_No response_

### 版本 | Version

0.52

### 部署方式？ | How do you deploy vanblog?

Docker 部署(文档默认)

**Comment by Mereithhh** [comment]
你是老版本更新的，还是重新部署的新版本呀？  在这个日志前，有报错吗？  后台图床设置开自定义插件了吗？

**Comment by Mereithhh** [comment]
你可以先关掉自动压缩图片试试看

**Comment by 6uu1** [comment]
> 你是老版本更新的，还是重新部署的新版本呀？ 在这个日志前，有报错吗？ 后台图床设置开自定义插件了吗？

老版本更新，未更新之前是好的，开了自定义插件是这个：web-uploader-custom-url-prefix ，是还需要再添加那个压缩的插件吗？

**Comment by 6uu1** [comment]
> 你可以先关掉自动压缩图片试试看

关闭了之后就好了

**Comment by Mereithhh** [comment]
修了一下，等更新到下一个版本应该开启压缩也不会报错了。

**Comment by Mereithhh** [comment]
复查了当前 `master`：这个压缩 + 自定义 PicGo 的 tmp 路径 `ENOENT` 已经修好了，不是使用者环境问题。

当时的栈是 `PicgoProvider.saveFile` 在 `finally` 里对 `/app/static/tmp/<hash>.clipboard-….webp` 做 `rmSync`。自动压缩（`cwebp`）写的是 `/tmp/temp….webp`，自定义插件 `web-uploader-custom-url-prefix` 上传成功后源文件已经不在原来的 `static/tmp` 路径上，未捕获的 `ENOENT` 被 Nest `ExceptionsHandler` 当成上传失败。关掉自动压缩就能过，和日志一致。

对应修复是 [43f84e6](https://github.com/Mereithhh/vanblog/commit/43f84e63a48ab3b483bc58ea5c5ab75bc4cffcc8)（就是 2023-05-05 说的「修了一下」）：
- `rmSync` 包了 try/catch，源文件被压缩/插件挪走时不再 500
- 压缩失败也不会再把整次上传打挂

这个提交已经在 `master` 上，并随 **v0.53.0**（2023-05-06）发布。当前代码里压缩仍写 `/tmp`、PicGo 仍写 `static/tmp`，但清理失败不会再让上传失败。

升级到 v0.53.0 及以上后，开着自动压缩 + 自定义 PicGo 插件上传应该就正常了。这边把 issue 关掉。

**Comment by 6uu1** [comment]
居然这么久的更新了
