### ISSUE TITLE
[问题反馈]: 部署后直接进入登陆界面，无法进入初始化界面

### ISSUE THREAD

**Issue by kklod** [Mereithhh/vanblog#371]
### 问题描述 | Describe the bug

win10下WSL Debian Docker部署，出现问题如上描述…………

输入初始化链接后自动跳转到登陆界面如下：
<img width="478" alt="image" src="https://github.com/Mereithhh/vanblog/assets/50442661/79708990-7601-4dda-91e1-a0cd90918f66">

**blog日志**
```
欢迎使用 VanBlog 博客系统
Github: https://github.com/mereithhh/vanblog
Version(Env): v0.54.0
=============================================
INF ts=1698990154.932345 msg=using provided configuration config_file=/app/caddy.json config_adapter=
INF ts=1698990154.9354296 msg=redirected default logger from=stderr to=/var/log/caddy.log
INF ts=1698990154.950178 msg=failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 2048 kiB, got: 416 kiB). See https://github.com/quic-go/quic-go/wiki/UDP-Receive-Buffer-Size for details.
Successfully started Caddy (pid=16) - Caddy is running in the background
未检测到 Vanblog 配置文件, 即将从环境变量中读取, 或采用默认配置
/app/server/node_modules/.pnpm/mongodb@5.6.0/node_modules/mongodb/lib/sdam/topology.js:278
                const timeoutError = new error_1.MongoServerSelectionError(`Server selection timed out after ${serverSelectionTimeoutMS} ms`, this.description);
                                     ^
MongoServerSelectionError: getaddrinfo ENOTFOUND mongo
    at Timeout._onTimeout (/app/server/node_modules/.pnpm/mongodb@5.6.0/node_modules/mongodb/lib/sdam/topology.js:278:38)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7) {
  reason: TopologyDescription {
    type: 'Unknown',
    servers: Map(1) {
      'mongo:27017' => ServerDescription {
        address: 'mongo:27017',
        type: 'Unknown',
        hosts: [],
        passives: [],
        arbiters: [],
        tags: {},
        minWireVersion: 0,
        maxWireVersion: 0,
        roundTripTime: -1,
        lastUpdateTime: 448792794,
        lastWriteDate: 0,
        error: MongoNetworkError: getaddrinfo ENOTFOUND mongo
            at connectionFailureError (/app/server/node_modules/.pnpm/mongodb@5.6.0/node_modules/mongodb/lib/cmap/connect.js:370:20)
            at Socket.<anonymous> (/app/server/node_modules/.pnpm/mongodb@5.6.0/node_modules/mongodb/lib/cmap/connect.js:293:22)
            at Object.onceWrapper (node:events:628:26)
            at Socket.emit (node:events:513:28)
            at emitErrorNT (node:internal/streams/destroy:151:8)
            at emitErrorCloseNT (node:internal/streams/destroy:116:3)
            at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
          cause: Error: getaddrinfo ENOTFOUND mongo
              at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26) {
            errno: -3008,
            code: 'ENOTFOUND',
            syscall: 'getaddrinfo',
            hostname: 'mongo'

          },
          [Symbol(errorLabels)]: Set(1) { 'ResetPool' }
        },
        topologyVersion: null,
        setName: null,
        setVersion: null,
        electionId: null,
        logicalSessionTimeoutMinutes: null,
        primary: null,
        me: null,
        '$clusterTime': null
      }
    },
    stale: false,
    compatible: true,
    heartbeatFrequencyMS: 10000,
    localThresholdMS: 15,
    setName: null,
    maxElectionId: null,
    maxSetVersion: null,
    commonWireVersion: 0,
    logicalSessionTimeoutMinutes: null
  },
  code: undefined,
  [Symbol(errorLabels)]: Set(0) {}
}
Node.js v18.16.1
[vanblog] 已停止.=============================================
```
**mongo日志：**
```
t={"$date":"2023-11-03T13:42:35.786+08:00"} s=I c=CONTROL id=23285 ctx=main msg=Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'
t={"$date":"2023-11-03T13:42:35.787+08:00"} s=I c=NETWORK id=4648601 ctx=main msg=Implicit TCP FastOpen unavailable. If TCP FastOpen is required, set tcpFastOpenServer, tcpFastOpenClient, and tcpFastOpenQueueSize.
t={"$date":"2023-11-03T13:42:35.788+08:00"} s=I c=STORAGE id=4615611 ctx=initandlisten msg=MongoDB starting attr={"pid":1,"port":27017,"dbPath":"/data/db","architecture":"64-bit","host":"48e1370cef52"}
t={"$date":"2023-11-03T13:42:35.788+08:00"} s=I c=CONTROL id=23403 ctx=initandlisten msg=Build Info attr={"buildInfo":{"version":"4.4.16","gitVersion":"a7bceadbac919a2c035f2874c61d138fd75d6a6f","openSSLVersion":"OpenSSL 1.1.1f  31 Mar 2020","modules":[],"allocator":"tcmalloc","environment":{"distmod":"ubuntu2004","distarch":"x86_64","target_arch":"x86_64"}}}
t={"$date":"2023-11-03T13:42:35.788+08:00"} s=I c=CONTROL id=51765 ctx=initandlisten msg=Operating System attr={"os":{"name":"Ubuntu","version":"20.04"}}
t={"$date":"2023-11-03T13:42:35.788+08:00"} s=I c=CONTROL id=21951 ctx=initandlisten msg=Options set by command line attr={"options":{"net":{"bindIp":"*"}}}
t={"$date":"2023-11-03T13:42:35.799+08:00"} s=I c=STORAGE id=22315 ctx=initandlisten msg=Opening WiredTiger attr={"config":"create,cache_size=3426M,session_max=33000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000,close_scan_interval=10,close_handle_minimum=250),statistics_log=(wait=0),verbose=[recovery_progress,checkpoint_progress,compact_progress],"}
t={"$date":"2023-11-03T13:42:36.405+08:00"} s=E c=STORAGE id=22435 ctx=initandlisten msg=WiredTiger error attr={"error":17,"message":"[1698990156:405720][1:0x7fd62a118cc0], connection: __posix_open_file, 808: /data/db/WiredTiger.wt: handle-open: open: File exists"}
t={"$date":"2023-11-03T13:42:36.503+08:00"} s=I c=STORAGE id=22430 ctx=initandlisten msg=WiredTiger message attr={"message":"unexpected file WiredTiger.wt found, renamed to WiredTiger.wt.54"}
t={"$date":"2023-11-03T13:42:36.506+08:00"} s=E c=STORAGE id=22435 ctx=initandlisten msg=WiredTiger error attr={"error":1,"message":"[1698990156:506496][1:0x7fd62a118cc0], connection: __posix_open_file, 808: /data/db/WiredTiger.wt: handle-open: open: Operation not permitted"}
t={"$date":"2023-11-03T13:42:36.537+08:00"} s=E c=STORAGE id=22435 ctx=initandlisten msg=WiredTiger error attr={"error":17,"message":"[1698990156:537474][1:0x7fd62a118cc0], connection: __posix_open_file, 808: /data/db/WiredTiger.wt: handle-open: open: File exists"}
t={"$date":"2023-11-03T13:42:36.634+08:00"} s=I c=STORAGE id=22430 ctx=initandlisten msg=WiredTiger message attr={"message":"unexpected file WiredTiger.wt found, renamed to WiredTiger.wt.55"}
t={"$date":"2023-11-03T13:42:36.638+08:00"} s=E c=STORAGE id=22435 ctx=initandlisten msg=WiredTiger error attr={"error":1,"message":"[1698990156:638368][1:0x7fd62a118cc0], connection: __posix_open_file, 808: /data/db/WiredTiger.wt: handle-open: open: Operation not permitted"}
t={"$date":"2023-11-03T13:42:36.718+08:00"} s=E c=STORAGE id=22435 ctx=initandlisten msg=WiredTiger error attr={"error":17,"message":"[1698990156:718680][1:0x7fd62a118cc0], connection: __posix_open_file, 808: /data/db/WiredTiger.wt: handle-open: open: File exists"}
t={"$date":"2023-11-03T13:42:36.819+08:00"} s=I c=STORAGE id=22430 ctx=initandlisten msg=WiredTiger message attr={"message":"unexpected file WiredTiger.wt found, renamed to WiredTiger.wt.56"}
t={"$date":"2023-11-03T13:42:36.823+08:00"} s=E c=STORAGE id=22435 ctx=initandlisten msg=WiredTiger error attr={"error":1,"message":"[1698990156:823104][1:0x7fd62a118cc0], connection: __posix_open_file, 808: /data/db/WiredTiger.wt: handle-open: open: Operation not permitted"}
t={"$date":"2023-11-03T13:42:36.827+08:00"} s=W c=STORAGE id=22347 ctx=initandlisten msg=Failed to start up WiredTiger under any compatibility version. This may be due to an unsupported upgrade or downgrade.
t={"$date":"2023-11-03T13:42:36.827+08:00"} s=F c=STORAGE id=28595 ctx=initandlisten msg=Terminating. attr={"reason":"1: Operation not permitted"}
t={"$date":"2023-11-03T13:42:36.827+08:00"} s=F c=- id=23091 ctx=initandlisten msg=Fatal assertion attr={"msgid":28595,"file":"src/mongo/db/storage/wiredtiger/wiredtiger_kv_engine.cpp","line":958}
t={"$date":"2023-11-03T13:42:36.827+08:00"} s=F c=- id=23092 ctx=initandlisten msg=

***aborting after fassert() failure

t={"$date":"2023-11-03T13:43:37.706+08:00"} s=I c=CONTROL id=23285 ctx=main msg=Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'
t={"$date":"2023-11-03T13:43:37.709+08:00"} s=I c=NETWORK id=4648601 ctx=main msg=Implicit TCP FastOpen unavailable. If TCP FastOpen is required, set tcpFastOpenServer, tcpFastOpenClient, and tcpFastOpenQueueSize.
t={"$date":"2023-11-03T13:43:37.710+08:00"} s=I c=STORAGE id=4615611 ctx=initandlisten msg=MongoDB starting attr={"pid":1,"port":27017,"dbPath":"/data/db","architecture":"64-bit","host":"48e1370cef52"}
t={"$date":"2023-11-03T13:43:37.710+08:00"} s=I c=CONTROL id=23403 ctx=initandlisten msg=Build Info attr={"buildInfo":{"version":"4.4.16","gitVersion":"a7bceadbac919a2c035f2874c61d138fd75d6a6f","openSSLVersion":"OpenSSL 1.1.1f  31 Mar 2020","modules":[],"allocator":"tcmalloc","environment":{"distmod":"ubuntu2004","distarch":"x86_64","target_arch":"x86_64"}}}
t={"$date":"2023-11-03T13:43:37.710+08:00"} s=I c=CONTROL id=51765 ctx=initandlisten msg=Operating System attr={"os":{"name":"Ubuntu","version":"20.04"}}
t={"$date":"2023-11-03T13:43:37.710+08:00"} s=I c=CONTROL id=21951 ctx=initandlisten msg=Options set by command line attr={"options":{"net":{"bindIp":"*"}}}
t={"$date":"2023-11-03T13:43:37.722+08:00"} s=I c=STORAGE id=22315 ctx=initandlisten msg=Opening WiredTiger attr={"config":"create,cache_size=3426M,session_max=33000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000,close_scan_interval=10,close_handle_minimum=250),statistics_log=(wait=0),verbose=[recovery_progress,checkpoint_progress,compact_progress],"}
t={"$date":"2023-11-03T13:43:38.294+08:00"} s=E c=STORAGE id=22435 ctx=initandlisten msg=WiredTiger error attr={"error":17,"message":"[1698990218:294472][1:0x7fcec44d1cc0], connection: __posix_open_file, 808: /data/db/WiredTiger.wt: handle-open: open: File exists"}
t={"$date":"2023-11-03T13:43:38.397+08:00"} s=I c=STORAGE id=22430 ctx=initandlisten msg=WiredTiger message attr={"message":"unexpected file WiredTiger.wt found, renamed to WiredTiger.wt.57"}
t={"$date":"2023-11-03T13:43:38.400+08:00"} s=E c=STORAGE id=22435 ctx=initandlisten msg=WiredTiger error attr={"error":1,"message":"[1698990218:400799][1:0x7fcec44d1cc0], connection: __posix_open_file, 808: /data/db/WiredTiger.wt: handle-open: open: Operation not permitted"}
t={"$date":"2023-11-03T13:43:38.440+08:00"} s=E c=STORAGE id=22435 ctx=initandlisten msg=WiredTiger error attr={"error":17,"message":"[1698990218:440806][1:0x7fcec44d1cc0], connection: __posix_open_file, 808: /data/db/WiredTiger.wt: handle-open: open: File exists"}
t={"$date":"2023-11-03T13:43:38.547+08:00"} s=I c=STORAGE id=22430 ctx=initandlisten msg=WiredTiger message attr={"message":"unexpected file WiredTiger.wt found, renamed to WiredTiger.wt.58"}
t={"$date":"2023-11-03T13:43:38.550+08:00"} s=E c=STORAGE id=22435 ctx=initandlisten msg=WiredTiger error attr={"error":1,"message":"[1698990218:550777][1:0x7fcec44d1cc0], connection: __posix_open_file, 808: /data/db/WiredTiger.wt: handle-open: open: Operation not permitted"}
t={"$date":"2023-11-03T13:43:38.591+08:00"} s=E c=STORAGE id=22435 ctx=initandlisten msg=WiredTiger error attr={"error":17,"message":"[1698990218:591770][1:0x7fcec44d1cc0], connection: __posix_open_file, 808: /data/db/WiredTiger.wt: handle-open: open: File exists"}
t={"$date":"2023-11-03T13:43:38.696+08:00"} s=I c=STORAGE id=22430 ctx=initandlisten msg=WiredTiger message attr={"message":"unexpected file WiredTiger.wt found, renamed to WiredTiger.wt.59"}
t={"$date":"2023-11-03T13:43:38.700+08:00"} s=E c=STORAGE id=22435 ctx=initandlisten msg=WiredTiger error attr={"error":1,"message":"[1698990218:700559][1:0x7fcec44d1cc0], connection: __posix_open_file, 808: /data/db/WiredTiger.wt: handle-open: open: Operation not permitted"}
t={"$date":"2023-11-03T13:43:38.704+08:00"} s=W c=STORAGE id=22347 ctx=initandlisten msg=Failed to start up WiredTiger under any compatibility version. This may be due to an unsupported upgrade or downgrade.
t={"$date":"2023-11-03T13:43:38.704+08:00"} s=F c=STORAGE id=28595 ctx=initandlisten msg=Terminating. attr={"reason":"1: Operation not permitted"}
t={"$date":"2023-11-03T13:43:38.704+08:00"} s=F c=- id=23091 ctx=initandlisten msg=Fatal assertion attr={"msgid":28595,"file":"src/mongo/db/storage/wiredtiger/wiredtiger_kv_engine.cpp","line":958}
t={"$date":"2023-11-03T13:43:38.704+08:00"} s=F c=- id=23092 ctx=initandlisten msg=

***aborting after fassert() failure
```

### 版本 | Version

v0.54.0

### 部署方式？ | How do you deploy vanblog?

Docker 部署(文档默认)

**Comment by CornWorld** [comment]
注意到有一个报错是：`open: Operation not permitted`  
怀疑是映射到 mongo  容器的 `/data/db` 的文件夹没有合适的权限。

**Comment by kklod** [comment]
> 注意到有一个报错是：`open: Operation not permitted` 怀疑是映射到 mongo 容器的 `/data/db` 的文件夹没有合适的权限。 @kklod

应该不适权限的问题   目前删除容器后重新部署成功……
