### ISSUE TITLE
[问题反馈]: 内部服务错误

### ISSUE THREAD

**Issue by bqey** [Mereithhh/vanblog#400]
### 问题描述 | Describe the bug

重启nginx后，出现后台打开文章为空并报错；使用了cdn加速，且ssl证书并未使用系统提供的方式，通过nginx配置的
[Nest] 27  - 02/01/2024, 11:47:48 AM   ERROR [ExceptionsHandler] Skip value must be non-negative, but received: -9223372036854775808
MongoServerError: Skip value must be non-negative, but received: -9223372036854775808
    at Connection.onMessage (/app/server/node_modules/.pnpm/mongodb@5.6.0/node_modules/mongodb/lib/cmap/connection.js:202:26)
    at MessageStream.<anonymous> (/app/server/node_modules/.pnpm/mongodb@5.6.0/node_modules/mongodb/lib/cmap/connection.js:61:60)
    at MessageStream.emit (node:events:513:28)
    at processIncomingData (/app/server/node_modules/.pnpm/mongodb@5.6.0/node_modules/mongodb/lib/cmap/message_stream.js:124:16)
    at MessageStream._write (/app/server/node_modules/.pnpm/mongodb@5.6.0/node_modules/mongodb/lib/cmap/message_stream.js:33:9)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)
    at Writable.write (node:internal/streams/writable:337:10)
    at Socket.ondata (node:internal/streams/readable:766:22)
    at Socket.emit (node:events:513:28)
![image](https://github.com/Mereithhh/vanblog/assets/86216991/e0d69667-ed2c-4dab-a746-418ab76128ac)

### 版本 | Version

0.54.0

### 部署方式？ | How do you deploy vanblog?

Docker 部署(文档默认)

**Comment by bqey** [comment]
点击文章管理的时候报的错

**Comment by Mereithhh** [comment]
## Cycle 48

Starting from master `94fae32` (after #558):

**In scope:** 后台文章列表 Mongo `skip` 为负数（`-9223372036854775808`）导致「内部服务错误」。

Will link the PR when it opens.

**Comment by Mereithhh** [comment]
## Cycle 48 — PR up (draft)

Focused slice（分页 skip 消毒）:
https://github.com/Mereithhh/vanblog/pull/559

`Fixes #400`. Waiting on CI.

**Comment by Mereithhh** [comment]
## Cycle 48 — ready

https://github.com/Mereithhh/vanblog/pull/559 undrafted; CI green on `ede8f5f` (GitGuardian + server-test + admin-e2e + alpine-sharp-install).

分页 skip 已消毒；`Fixes #400`。

Escalating squash-merge to CoS.

**Comment by Mereithhh** [comment]
已合入 master（squash `ceff6d7`，PR #559）。

文章/草稿/图片/日志等列表的 `page` / `pageSize` 会经 `sanitizePagination` 清洗：非法或溢出值不再算出负数 Mongo `skip`（不会再变成 `-9223372036854775808`），文章管理不会整页「内部服务错误」。

测试：`pagination.spec.ts` + article controller/provider 敌意分页用例（server-test）。未推送 `v*` / `doc*` / `test*` 标签。
