### ISSUE TITLE
[问题反馈]:6月份 4号编辑草稿文档，5号打开的时候发现文档变成空的了，但是编辑文档上传的图片还在

### ISSUE THREAD

**Issue by MonkeyEric** [Mereithhh/vanblog#427]
### 问题描述 | Describe the bug

查看error日志，发现此内容
```log
[Nest] 26  - 06/04/2024, 11:13:03 PM   ERROR [ExceptionsHandler] Cast to Number failed for value "NaN" (type number) at path "id" for model "Article"
CastError: Cast to Number failed for value "NaN" (type number) at path "id" for model "Article"
    at SchemaNumber.cast (/app/server/node_modules/.pnpm/mongoose@7.3.1/node_modules/mongoose/lib/schema/number.js:378:11)
    at SchemaType.applySetters (/app/server/node_modules/.pnpm/mongoose@7.3.1/node_modules/mongoose/lib/schematype.js:1204:12)
    at SchemaNumber.castForQuery (/app/server/node_modules/.pnpm/mongoose@7.3.1/node_modules/mongoose/lib/schema/number.js:430:14)
    at cast (/app/server/node_modules/.pnpm/mongoose@7.3.1/node_modules/mongoose/lib/cast.js:356:32)
    at Query.cast (/app/server/node_modules/.pnpm/mongoose@7.3.1/node_modules/mongoose/lib/query.js:4866:12)
    at Query._castConditions (/app/server/node_modules/.pnpm/mongoose@7.3.1/node_modules/mongoose/lib/query.js:2210:10)
    at model.Query._findOne (/app/server/node_modules/.pnpm/mongoose@7.3.1/node_modules/mongoose/lib/query.js:2497:8)
    at model.Query.exec (/app/server/node_modules/.pnpm/mongoose@7.3.1/node_modules/mongoose/lib/query.js:4396:28)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ArticleProvider.getById (/app/server/provider/article/article.provider.js:637:16)
```

### 复现网址 | Website URL

http://47.100.218.236/

### 版本 | Version

v0.54.0

### 部署方式？ | How do you deploy vanblog?

Docker 部署(文档默认)

**Comment by Mereithhh** [comment]
已在当前 `master` 上复现：编辑器缺失/非数字 ID 会被 `Number()` 成 `NaN`，`ArticleProvider.getById` 拿去查 mongoose，就会出你日志里的 `Cast to Number failed for value "NaN" at path "id"`。加载失败后编辑器会显示空正文（图床里上传的图还在），再保存还有把草稿写空的风险。

修复见 PR：https://github.com/Mereithhh/vanblog/pull/XXX

非法 ID 现在会直接 400，不再拿 `NaN` 去查/更新。合并进 `master` 前先不关这个 issue。

**Comment by Mereithhh** [comment]
修复 PR：https://github.com/Mereithhh/vanblog/pull/519

合并进 `master` 前先不关这个 issue。

**Comment by Mereithhh** [comment]
修复已合入 `master`：https://github.com/Mereithhh/vanblog/pull/519

非法或缺失的文章/草稿 ID 不会再被 `Number()` 成 `NaN` 去查 MongoDB，打开草稿也不会把正文写成空的。此修复随下一次正式发版上线。若正文其实还在库里，从草稿列表重新点「编辑」即可。
