### ISSUE TITLE
[问题反馈]: 个别文章渲染失败，报错500

### ISSUE THREAD

**Issue by DingDangDog** [Mereithhh/vanblog#63]
### 问题描述 | Describe the bug

[GitHub使用SSH连接](https://oldmoon.top/post/9)

# 查看文章时报错日志：
```
[Nest] 19  - 10/04/2022, 2:12:55 PM   ERROR [WebsiteProvider] Error: Minified React error #62; visit https://reactjs.org/docs/error-decoder.html?invariant=62 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Fa (/app/website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:27:49)
    at I (/app/website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:29:44)
    at Pa (/app/website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:38:13)
    at Mc (/app/website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:67:38)
    at Z (/app/website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:71:89)
    at Mc (/app/website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:66:481)
    at Z (/app/website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:71:89)
    at Mc (/app/website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:67:438)
    at Z (/app/website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:71:89)
    at Mc (/app/website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:66:481)
Error: Minified React error #62; visit https://reactjs.org/docs/error-decoder.html?invariant=62 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Fa (/app/website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:27:49)
    at I (/app/website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:29:44)
    at Pa (/app/website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:38:13)
    at Mc (/app/website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:67:38)
    at Z (/app/website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:71:89)
    at Mc (/app/website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:66:481)
    at Z (/app/website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:71:89)
    at Mc (/app/website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:67:438)
    at Z (/app/website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:71:89)
    at Mc (/app/website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:66:481)
```

# 编辑文章保存时报错日志（数据可以保存成功）：
```
[Nest] 19  - 10/04/2022, 2:14:33 PM   ERROR [WebsiteProvider] Error: Minified React error #62; visit https://reactjs.org/docs/error-decoder.html?invariant=62 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Fa (/app/website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:27:49)
    at I (/app/website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:29:44)
    at Pa (/app/website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:38:13)
    at Mc (/app/website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:67:38)
    at Z (/app/website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:71:89)
    at Mc (/app/website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:66:481)
    at Z (/app/website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:71:89)
    at Mc (/app/website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:67:438)
    at Z (/app/website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:71:89)
    at Mc (/app/website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:66:481)
Error: Minified React error #62; visit https://reactjs.org/docs/error-decoder.html?invariant=62 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Fa (/app/website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:27:49)
    at I (/app/website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:29:44)
    at Pa (/app/website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:38:13)
    at Mc (/app/website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:67:38)
    at Z (/app/website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:71:89)
    at Mc (/app/website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:66:481)
    at Z (/app/website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:71:89)
    at Mc (/app/website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:67:438)
    at Z (/app/website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:71:89)
    at Mc (/app/website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:66:481)
[Nest] 19  - 10/04/2022, 2:14:33 PM   ERROR [WebsiteProvider] TypeError: res.hasHeader is not a function
    at Object.setRevalidateHeaders (/app/website/node_modules/next/dist/server/send-payload/revalidate-headers.js:8:37)
    at Object.sendRenderResult (/app/website/node_modules/next/dist/server/send-payload/index.js:62:33)
    at NextNodeServer.sendRenderResult (/app/website/node_modules/next/dist/server/next-server.js:381:34)
    at NextNodeServer.pipe (/app/website/node_modules/next/dist/server/base-server.js:381:25)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.fn (/app/website/node_modules/next/dist/server/next-server.js:743:21)
    at async Router.execute (/app/website/node_modules/next/dist/server/router.js:247:36)
    at async NextNodeServer.run (/app/website/node_modules/next/dist/server/base-server.js:347:29)
    at async NextNodeServer.handleRequest (/app/website/node_modules/next/dist/server/base-server.js:285:20)
    at async revalidate (/app/website/node_modules/next/dist/server/api-utils/node.js:286:13)
[Nest] 19  - 10/04/2022, 2:14:33 PM   ERROR [ISRProvider] 触发增量渲染失败！ /post/9
```

### 复现网址 | Website URL

https://oldmoon.top/post/9

### 版本 | Version

v0.41.3

### 部署方式？ | How do you deploy vanblog?

Docker 部署(文档默认)

**Comment by Mereithhh** [comment]
感谢反馈，我会尽快处理。国庆比较懒，最晚国庆结束3天内搞定。

**Comment by Mereithhh** [comment]
## 原因
是因为 markdown 中的 img 标签的 style 属性导致的：
![image](https://user-images.githubusercontent.com/22872368/194461396-4149b9e4-1b56-458e-a192-ca516e749b42.png)

因为我给 markdown 渲染的 img 标签做了优化，但和 style 属性有些冲突，现在已经修复了。 

## 局限

现在 markdown 内的 img 标签只支持 width、height、class 三个属性，如果需要自定义 style 请在外面包裹一层 div 之类的标签，在父元素指定 style 属性即可。

下次发版会上线，此 issue 就先关了
